-- Release ledger baseline schema for Supabase (Postgres)
-- Run once in SQL editor.

create table if not exists public.release_ledger (
  id bigint generated by default as identity primary key,
  run_id text not null unique,
  release_type text not null default 'BOT_EXECUTION',
  trigger_type text,
  cron_type text,
  branch text not null default 'main',
  commit_sha text,
  backlog_id text,
  status text not null default 'RUNNING',
  note text,
  released_at timestamptz not null default now(),
  completed_at timestamptz
);

create index if not exists idx_release_ledger_released_at
  on public.release_ledger (released_at desc);

create index if not exists idx_release_ledger_status
  on public.release_ledger (status);

create index if not exists idx_release_ledger_backlog_id
  on public.release_ledger (backlog_id);

